import "../styles/globals.scss";
import type { AppProps } from "next/app";
import Head from "next/head";
import { Poppins } from "@next/font/google";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["300", "400", "500"],
});

export default function App({ Component, pageProps }: AppProps) {
    return (
        <>
            <Head>
                <title>Growfy</title>
                <meta
                    name="Pet Project by Sikorsky"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={poppins.className}>
                <Component {...pageProps} />
            </div>
        </>
    );
}
